// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL) {
  throw new Error("VITE_SUPABASE_URL is required");
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error("A Supabase key is required. Set VITE_SUPABASE_PUBLISHABLE_KEY or VITE_SUPABASE_ANON_KEY");
}

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Do NOT persist the session across browser tabs/restarts.
    // This is a sensitive site — every new browser session must re-authenticate.
    // It also prevents stale localStorage tokens from causing infinite loading
    // on Render cold starts.
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: false,
  },
});
